/**
 * MIT License
 *
 * Copyright (C) 2024 Huawei Device Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterCpp.js
 */

#include "EventEmitters.h"


namespace facebook {
namespace react {

void NativeCameraEventEmitter::onBarCodeRead(OnBarCodeRead $event) const {
    dispatchEvent("barCodeRead", [$event = std::move($event)](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);
        $payload.setProperty(runtime, "data", $event.data);
        $payload.setProperty(runtime, "rawData", $event.rawData);
        $payload.setProperty(runtime, "type", $event.type);
        {
            auto bounds = jsi::Object(runtime);
            {
                auto origin = jsi::Object(runtime);
                origin.setProperty(runtime, "x", $event.bounds.origin.x);
                origin.setProperty(runtime, "y", $event.bounds.origin.y);
                bounds.setProperty(runtime, "origin", origin);
            }
            {
                auto size = jsi::Object(runtime);
                size.setProperty(runtime, "width", $event.bounds.size.width);
                size.setProperty(runtime, "height", $event.bounds.size.height);
                bounds.setProperty(runtime, "size", size);
            }
            $payload.setProperty(runtime, "bounds", bounds);
        }
        $payload.setProperty(runtime, "image", $event.image);
        return $payload;
    });
}

void NativeCameraEventEmitter::onSubjectAreaChanged(OnSubjectAreaChanged $event) const {
    dispatchEvent("subjectAreaChanged", [](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);
        return $payload;
    });
}

void NativeCameraEventEmitter::onGoogleVisionBarcodesDetected(OnGoogleVisionBarcodesDetected $event) const {
    dispatchEvent("googleVisionBarcodesDetected", [$event = std::move($event)](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);
        $payload.setProperty(runtime, "overlook", $event.overlook);
//        {
//            auto target = jsi::Object(runtime);
//            target.setProperty(runtime, "latitude", $event.target.latitude);
//            target.setProperty(runtime, "longitude", $event.target.longitude);
//            $payload.setProperty(runtime, "target", target);
//        }
        return $payload;
    });
}


void NativeCameraEventEmitter::onCameraReady(OnCameraReady $event) const {
    dispatchEvent("cameraReady", [](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);
        return $payload;
    });
}
void NativeCameraEventEmitter::onRecordingStart(OnRecordingStart $event) const {
    dispatchEvent("recordingStart", [$event = std::move($event)](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);
        {
            auto nativeEvent = jsi::Object(runtime);
            nativeEvent.setProperty(runtime, "uri", "ffds");
            nativeEvent.setProperty(runtime, "videoOrientation", 2);
            nativeEvent.setProperty(runtime, "deviceOrientation", 33);
            $payload.setProperty(runtime, "nativeEvent", nativeEvent);
        }
        return $payload;
    });
}


void NativeCameraEventEmitter::onRecordingEnd(OnStopRecording $event) const {
    dispatchEvent("recordingEnd", [](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);
        return $payload;
    });
}


void NativeCameraEventEmitter::onAudioInterrupted(OnAudioInterrupted $event) const {
    dispatchEvent("audioInterrupted", [](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);

        return $payload;
    });
}


void NativeCameraEventEmitter::onAudioConnected(OnAudioConnected $event) const {
    dispatchEvent("audioConnected", [$event = std::move($event)](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);
        return $payload;
    });
}

void NativeCameraEventEmitter::onPictureSaved(OnPictureSaved $event) const {
    dispatchEvent("pictureSaved", [$event = std::move($event)](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);
//        {
//            auto position = jsi::Object(runtime);
//            position.setProperty(runtime, "latitude", $event.position.latitude);
//            position.setProperty(runtime, "longitude", $event.position.longitude);
//            $payload.setProperty(runtime, "position", position);
//        }
//        $payload.setProperty(runtime, "title", $event.title);
        return $payload;
    });
}


void NativeCameraEventEmitter::onFaceDetected(OnFaceDetected $event) const {
    dispatchEvent("faceDetected", [](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);

        return $payload;
    });
}

void NativeCameraEventEmitter::onTouch(TapCallback $event) const {
    dispatchEvent("touch", [$event = std::move($event)](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);
        $payload.setProperty(runtime, "isDoubleTap", $event.isDoubleTap);
        {
            auto touchOrigin = jsi::Object(runtime);
            touchOrigin.setProperty(runtime, "x", $event.touchOrigin.x);
            touchOrigin.setProperty(runtime, "y", $event.touchOrigin.y);
            $payload.setProperty(runtime, "touchOrigin", touchOrigin);
        }
        return $payload;
    });
}

void NativeCameraEventEmitter::onMountError(OnMountError $event) const {
    dispatchEvent("mountError", [$event = std::move($event)](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);
        $payload.setProperty(runtime, "message", $event.message);
        return $payload;
    });
}

void NativeCameraEventEmitter::onTaskPhoto(OnTaskPhoto $event) const {
    dispatchEvent("taskPhoto", [](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);

        return $payload;
    });
}

void NativeCameraEventEmitter::onPictureTaken(OnPictureTaken $event) const {
    dispatchEvent("pictureTaken", [](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);

        return $payload;
    });
}

void NativeCameraEventEmitter::onStatusChange(OnStatusChange $event) const {
    dispatchEvent("statusChange", [$event = std::move($event)](jsi::Runtime &runtime) {
        auto $payload = jsi::Object(runtime);
        $payload.setProperty(runtime, "cameraStatus", $event.cameraStatus);
        $payload.setProperty(runtime, "recordAudioPermissionStatus", $event.recordAudioPermissionStatus);
        return $payload;
    });
}

} // namespace react
} // namespace facebook
