/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the MIT License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://github.com/react-native-camera/react-native-camera/blob/v4.2.1/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */

#include "RNOHCorePackage/ComponentBinders/ViewComponentJSIBinder.h"

namespace rnoh {
class NativeCameraJSIBinder : public ViewComponentJSIBinder {
protected:
    facebook::jsi::Object createNativeProps(facebook::jsi::Runtime &rt) override {
        auto object = ViewComponentJSIBinder::createNativeProps(rt);
        object.setProperty(rt, "accessibilityComponentType", true);
        object.setProperty(rt, "accessibilityLiveRegion", true);
        object.setProperty(rt, "barCodeScannerEnabled", true);
        object.setProperty(rt, "touchDetectorEnabled", true);
        object.setProperty(rt, "googleVisionBarcodeDetectorEnabled", true);
        object.setProperty(rt, "faceDetectorEnabled", true);
        object.setProperty(rt, "textRecognizerEnabled", true);
        object.setProperty(rt, "importantForAccessibility", true);
        object.setProperty(rt, "renderToHardwareTextureAndroid", true);
        object.setProperty(rt, "testID", true);
        object.setProperty(rt, "autoFocus", true);
        object.setProperty(rt, "autoFocusPointOfInterest", "Object");
        object.setProperty(rt, "cameraId", "");
        object.setProperty(rt, "pictureSize", "");
        object.setProperty(rt, "type", "");
        object.setProperty(rt, "flashMode", true);
        object.setProperty(rt, "exposure", true);
        object.setProperty(rt, "captureAudio", true);
        object.setProperty(rt, "useNativeZoom", true);
        object.setProperty(rt, "zoom", true);
        object.setProperty(rt, "maxZoom", true);
        object.setProperty(rt, "focusDepth", true);
        object.setProperty(rt, "detectedImageInEvent", true);

        object.setProperty(rt, "googleVisionBarcodeType", true);
        object.setProperty(rt, "googleVisionBarcodeMode", true);
        object.setProperty(rt, "rectOfInterest", "Object");
        object.setProperty(rt, "faceDetectionMode", "");
        object.setProperty(rt, "faceDetectionLandmarks", "");
        object.setProperty(rt, "faceDetectionClassifications", true);
        object.setProperty(rt, "trackingEnabled", true);
        object.setProperty(rt, "ratio", true);
        object.setProperty(rt, "playSoundOnCapture", true);
        object.setProperty(rt, "playSoundOnRecord", true);
        object.setProperty(rt, "videoStabilizationMode", "");
        object.setProperty(rt, "defaultVideoQuality", true);
        object.setProperty(rt, "keepAudioSession", true);
        object.setProperty(rt, "whiteBalance", true);
        return object;
    }

    facebook::jsi::Object createBubblingEventTypes(facebook::jsi::Runtime &rt) override {
        facebook::jsi::Object events(rt);
        return events;
    }

    facebook::jsi::Object createDirectEventTypes(facebook::jsi::Runtime &rt) override {
        facebook::jsi::Object events(rt);
        events.setProperty(rt, "topBarCodeRead", createDirectEvent(rt, "onBarCodeRead"));
        events.setProperty(rt, "topSubjectAreaChanged", createDirectEvent(rt, "onSubjectAreaChanged"));
        events.setProperty(rt, "topGoogleVisionBarcodesDetected",
                           createDirectEvent(rt, "onGoogleVisionBarcodesDetected"));
        events.setProperty(rt, "topCameraReady", createDirectEvent(rt, "onCameraReady"));
        events.setProperty(rt, "topAudioInterrupted", createDirectEvent(rt, "onAudioInterrupted"));
        events.setProperty(rt, "topAudioConnected", createDirectEvent(rt, "onAudioConnected"));
        events.setProperty(rt, "topPictureSaved", createDirectEvent(rt, "onPictureSaved"));
        events.setProperty(rt, "topFaceDetected", createDirectEvent(rt, "onFaceDetected"));
        events.setProperty(rt, "topTouch", createDirectEvent(rt, "onTouch"));
        events.setProperty(rt, "topMountError", createDirectEvent(rt, "onMountError"));
        events.setProperty(rt, "topTaskPhoto", createDirectEvent(rt, "onTaskPhoto"));
        events.setProperty(rt, "topRecordingStart", createDirectEvent(rt, "onRecordingStart"));
        events.setProperty(rt, "topRecordingEnd", createDirectEvent(rt, "onRecordingEnd"));
        events.setProperty(rt, "topPictureTaken", createDirectEvent(rt, "onPictureTaken"));
        events.setProperty(rt, "topStatusChange", createDirectEvent(rt, "onStatusChange"));
        
        return events;
    }
};
} // namespace rnoh
