/**
 * MIT License
 *
 * Copyright (C) 2024 Huawei Device Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>
#include <vector>

namespace facebook {
namespace react {
struct FocusPoint {
    Float x;
    Float y;
};

struct RectOfInterest {
    Float x;
    Float y;
    Float width;
    Float height;
}; // namespace react

static inline void fromRawValue(const PropsParserContext &context, const RawValue &value, FocusPoint &result) {
    auto map = (std::unordered_map<std::string, RawValue>)value;
    auto x = map.find("x");
    if (x != map.end()) {
        fromRawValue(context, x->second, result.x);
    }
    auto y = map.find("y");
    if (y != map.end()) {
        fromRawValue(context, y->second, result.y);
    }
}

static inline std::string toString(const FocusPoint &value) { return "[Object FocusPoint]"; }


static inline void fromRawValue(const PropsParserContext &context, const RawValue &value, RectOfInterest &result) {
    auto map = (std::unordered_map<std::string, RawValue>)value;

    auto x = map.find("x");
    if (x != map.end()) {
        fromRawValue(context, x->second, result.x);
    }
    auto y = map.find("y");
    if (y != map.end()) {
        fromRawValue(context, y->second, result.y);
    }

    auto width = map.find("width");
    if (width != map.end()) {
        fromRawValue(context, width->second, result.width);
    }
    auto height = map.find("height");
    if (y != map.end()) {
        fromRawValue(context, height->second, result.height);
    }
}

static inline std::string toString(const RectOfInterest &value) { return "[Object RectOfInterest]"; }


enum class VideoStabilizationMode { OFF, STANDARD, CINEMATIC, AUTO };

static inline void fromRawValue(const PropsParserContext &context, const RawValue &value,
                                VideoStabilizationMode &result) {
    auto string = (std::string)value;
    if (string == "off") {
        result = VideoStabilizationMode::OFF;
        return;
    }
    if (string == "standard") {
        result = VideoStabilizationMode::STANDARD;
        return;
    }
    if (string == "cinematic") {
        result = VideoStabilizationMode::CINEMATIC;
        return;
    }
    if (string == "auto") {
        result = VideoStabilizationMode::AUTO;
        return;
    }
    abort();
}

static inline std::string toString(const VideoStabilizationMode &value) {
    switch (value) {
    case VideoStabilizationMode::OFF:
        return "all";
    case VideoStabilizationMode::STANDARD:
        return "standard";
    case VideoStabilizationMode::CINEMATIC:
        return "cinematic";
    case VideoStabilizationMode::AUTO:
        return "auto";
    }
}


enum class VideoQuality { TWO_0NE_P, ONE_ZERO_P, SEVEN_TWO_P, FOUR_EIGHT_P, FOUR_THREE_P, TWO_EIGHT_P };

static inline void fromRawValue(const PropsParserContext &context, const RawValue &value, VideoQuality &result) {
    auto string = (std::string)value;
    if (string == "2160p") {
        result = VideoQuality::TWO_0NE_P;
        return;
    }
    if (string == "1080p") {
        result = VideoQuality::ONE_ZERO_P;
        return;
    }
    if (string == "720p") {
        result = VideoQuality::SEVEN_TWO_P;
        return;
    }
    if (string == "480p") {
        result = VideoQuality::FOUR_EIGHT_P;
        return;
    }
    if (string == "4:3") {
        result = VideoQuality::FOUR_THREE_P;
        return;
    }
    if (string == "288p") {
        result = VideoQuality::TWO_EIGHT_P;
        return;
    }
    abort();
}

static inline std::string toString(const VideoQuality &value) {
    switch (value) {
    case VideoQuality::TWO_0NE_P:
        return "2160p";
    case VideoQuality::ONE_ZERO_P:
        return "1080p";
    case VideoQuality::SEVEN_TWO_P:
        return "720p";
    case VideoQuality::FOUR_EIGHT_P:
        return "480p";
    case VideoQuality::FOUR_THREE_P:
        return "4:3";
    case VideoQuality::TWO_EIGHT_P:
        return "288P";
    }
}

enum class AutoFocusMode { ON, OFF };

static inline void fromRawValue(const PropsParserContext &context, const RawValue &value, AutoFocusMode &result) {
    auto string = (std::string)value;
    if (string == "on") {
        result = AutoFocusMode::ON;
        return;
    }
    if (string == "off") {
        result = AutoFocusMode::OFF;
        return;
    }
    abort();
}

static inline std::string toString(const AutoFocusMode &value) {
    switch (value) {
    case AutoFocusMode::ON:
        return "on";
    case AutoFocusMode::OFF:
        return "off";
    }
}

enum class CameraType { BACK, FRONT };

static inline void fromRawValue(const PropsParserContext &context, const RawValue &value, CameraType &result) {
    auto string = (std::string)value;
    if (string == "back") {
        result = CameraType::BACK;
        return;
    }
    if (string == "front") {
        result = CameraType::FRONT;
        return;
    }
    abort();
}

static inline std::string toString(const CameraType &value) {
    switch (value) {
    case CameraType::BACK:
        return "back";
    case CameraType::FRONT:
        return "front";
    }
}

enum class WhiteBalance { SUNNY, CLOUDY, SHADOW, INCANDESCENT, FLUORESCENT, AUTO };
static inline void fromRawValue(const PropsParserContext &context, const RawValue &value, WhiteBalance &result) {
    auto string = (std::string)value;
    if (string == "sunny") {
        result = WhiteBalance::SUNNY;
        return;
    }
    if (string == "cloudy") {
        result = WhiteBalance::CLOUDY;
        return;
    }
    if (string == "shadow") {
        result = WhiteBalance::SHADOW;
        return;
    }
    if (string == "incandescent") {
        result = WhiteBalance::INCANDESCENT;
        return;
    }
    if (string == "fluorescent") {
        result = WhiteBalance::FLUORESCENT;
        return;
    }
    if (string == "auto") {
        result = WhiteBalance::AUTO;
        return;
    }
    abort();
}

static inline std::string toString(const WhiteBalance &value) {
    switch (value) {
    case WhiteBalance::SUNNY:
        return "on";
    case WhiteBalance::CLOUDY:
        return "off";
    case WhiteBalance::SHADOW:
        return "shadow";
    case WhiteBalance::INCANDESCENT:
        return "incandescent";
    case WhiteBalance::FLUORESCENT:
        return "fluorescent";
    case WhiteBalance::AUTO:
        return "auto";
    }
}

enum class FlashMode { ON, OFF, TORCH, AUTO };
static inline void fromRawValue(const PropsParserContext &context, const RawValue &value, FlashMode &result) {
    auto string = (std::string)value;
    if (string == "on") {
        result = FlashMode::ON;
        return;
    }
    if (string == "off") {
        result = FlashMode::OFF;
        return;
    }
    if (string == "torch") {
        result = FlashMode::TORCH;
        return;
    }
    if (string == "auto") {
        result = FlashMode::AUTO;
        return;
    }
    abort();
}

static inline std::string toString(const FlashMode &value) {
    switch (value) {
    case FlashMode::ON:
        return "on";
    case FlashMode::OFF:
        return "off";
    case FlashMode::TORCH:
        return "torch";
    case FlashMode::AUTO:
        return "auto";
    }
}

class NativeCameraProps final : public ViewProps {
public:
    NativeCameraProps() = default;
    NativeCameraProps(const PropsParserContext &context, const NativeCameraProps &sourceProps,
                      const RawProps &rawProps);

#pragma mark - Props

    bool accessibilityComponentType{false};
//  bool accessibilityLabel{false};
    bool accessibilityLiveRegion{false};
    bool barCodeScannerEnabled{false};
    bool touchDetectorEnabled{false};
    bool googleVisionBarcodeDetectorEnabled{false};
    bool faceDetectorEnabled{false};
    bool textRecognizerEnabled{false};
    bool importantForAccessibility{false};
    bool renderToHardwareTextureAndroid{false};
    bool testID{false};
    AutoFocusMode autoFocus{AutoFocusMode::ON};
    FocusPoint autoFocusPointOfInterest{};
    std::string pictureSize{};
    CameraType type{CameraType::BACK};
    FlashMode flashMode{FlashMode::AUTO};
    Float exposure{0.0};
    bool captureAudio{false};
    bool useNativeZoom{false};
    Float zoom{0.0};
    Float maxZoom{0.0};
    Float focusDepth{0.0};
    bool detectedImageInEvent{false};
    Float googleVisionBarcodeType{0.0};
    Float googleVisionBarcodeMode{0.0};
    RectOfInterest rectOfInterest;
    Float faceDetectionMode{0.0};
    Float faceDetectionLandmarks{0.0};
    Float faceDetectionClassifications{0.0};
    bool trackingEnabled{false};
    std::string ratio{};
    bool playSoundOnCapture{false};
    VideoStabilizationMode videoStabilizationMode{VideoStabilizationMode::AUTO};
    VideoQuality defaultVideoQuality{VideoQuality::ONE_ZERO_P};
    bool keepAudioSession{false};
    WhiteBalance whiteBalance{WhiteBalance::AUTO};
};

} // namespace react
} // namespace facebook
