/**
 * MIT License
 *
 * Copyright (C) 2024 Huawei Device Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include "Props.h"
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

NativeCameraProps::NativeCameraProps(
    const PropsParserContext &context,
    const NativeCameraProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    accessibilityComponentType(convertRawProp(context, rawProps, "accessibilityComponentType", sourceProps.accessibilityComponentType, {false})),
//    accessibilityLabel(convertRawProp(context, rawProps, "accessibilityLabel", sourceProps.accessibilityLabel, {false})),
    accessibilityLiveRegion(convertRawProp(context, rawProps, "accessibilityLiveRegion", sourceProps.accessibilityLiveRegion, {false})),
    barCodeScannerEnabled(convertRawProp(context, rawProps, "barCodeScannerEnabled", sourceProps.barCodeScannerEnabled, {false})),
    touchDetectorEnabled(convertRawProp(context, rawProps, "touchDetectorEnabled", sourceProps.touchDetectorEnabled, {false})),
    googleVisionBarcodeDetectorEnabled(convertRawProp(context, rawProps, "googleVisionBarcodeDetectorEnabled", sourceProps.googleVisionBarcodeDetectorEnabled, {false})),
    faceDetectorEnabled(convertRawProp(context, rawProps, "faceDetectorEnabled", sourceProps.faceDetectorEnabled, {false})),
    textRecognizerEnabled(convertRawProp(context, rawProps, "textRecognizerEnabled", sourceProps.textRecognizerEnabled, {false})),
    renderToHardwareTextureAndroid(convertRawProp(context, rawProps, "renderToHardwareTextureAndroid", sourceProps.renderToHardwareTextureAndroid, {false})),
    testID(convertRawProp(context, rawProps, "testID", sourceProps.testID, {false})),
    autoFocus(convertRawProp(context, rawProps, "autoFocus", sourceProps.autoFocus, {AutoFocusMode::ON})),
    autoFocusPointOfInterest(convertRawProp(context, rawProps, "autoFocusPointOfInterest", sourceProps.autoFocusPointOfInterest, {})),
    pictureSize(convertRawProp(context, rawProps, "pictureSize", sourceProps.pictureSize, {""})),
    type(convertRawProp(context, rawProps, "type", sourceProps.type, {CameraType::BACK})),
    flashMode(convertRawProp(context, rawProps, "flashMode", sourceProps.flashMode, {FlashMode::AUTO})),
    exposure(convertRawProp(context, rawProps, "exposure", sourceProps.exposure, {0.0})),
    captureAudio(convertRawProp(context, rawProps, "captureAudio", sourceProps.captureAudio, {true})),
    useNativeZoom(convertRawProp(context, rawProps, "useNativeZoom", sourceProps.useNativeZoom, {true})),
    zoom(convertRawProp(context, rawProps, "zoom", sourceProps.zoom, {0.0})),
    maxZoom(convertRawProp(context, rawProps, "maxZoom", sourceProps.maxZoom, {0.0})),
    focusDepth(convertRawProp(context, rawProps, "focusDepth", sourceProps.focusDepth, {0.0})),
    detectedImageInEvent(convertRawProp(context, rawProps, "detectedImageInEvent", sourceProps.detectedImageInEvent, {true})),

    googleVisionBarcodeType(convertRawProp(context, rawProps, "googleVisionBarcodeType", sourceProps.googleVisionBarcodeType, {0.0})),
    googleVisionBarcodeMode(convertRawProp(context, rawProps, "googleVisionBarcodeMode", sourceProps.googleVisionBarcodeMode, {0.0})),
    rectOfInterest(convertRawProp(context, rawProps, "rectOfInterest", sourceProps.rectOfInterest, {})),
    faceDetectionMode(convertRawProp(context, rawProps, "faceDetectionMode", sourceProps.faceDetectionMode, {0.0})),
    faceDetectionLandmarks(convertRawProp(context, rawProps, "faceDetectionLandmarks", sourceProps.faceDetectionLandmarks, {0.0})),
    faceDetectionClassifications(convertRawProp(context, rawProps, "faceDetectionClassifications", sourceProps.faceDetectionClassifications, {0.0})),
    trackingEnabled(convertRawProp(context, rawProps, "trackingEnabled", sourceProps.trackingEnabled, {true})),
    ratio(convertRawProp(context, rawProps, "ratio", sourceProps.ratio, {true})),
    playSoundOnCapture(convertRawProp(context, rawProps, "playSoundOnCapture", sourceProps.playSoundOnCapture, {true})),
    videoStabilizationMode(convertRawProp(context, rawProps, "videoStabilizationMode", sourceProps.videoStabilizationMode, {VideoStabilizationMode::AUTO})),
    defaultVideoQuality(convertRawProp(context, rawProps, "defaultVideoQuality", sourceProps.defaultVideoQuality, {VideoQuality::ONE_ZERO_P})),
    whiteBalance(convertRawProp(context, rawProps, "whiteBalance", sourceProps.whiteBalance, {WhiteBalance::AUTO})),
    keepAudioSession(convertRawProp(context, rawProps, "keepAudioSession", sourceProps.keepAudioSession, {true}))
      {}


} // namespace react
} // namespace facebook
