/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the MIT License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://github.com/react-native-camera/react-native-camera/blob/v4.2.1/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include "Props.h"
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

NativeCameraProps::NativeCameraProps(
    const PropsParserContext &context,
    const NativeCameraProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    accessibilityComponentType(convertRawProp(context, rawProps, "accessibilityComponentType", sourceProps.accessibilityComponentType, {false})),
//    accessibilityLabel(convertRawProp(context, rawProps, "accessibilityLabel", sourceProps.accessibilityLabel, {false})),
    accessibilityLiveRegion(convertRawProp(context, rawProps, "accessibilityLiveRegion", sourceProps.accessibilityLiveRegion, {false})),
    barCodeScannerEnabled(convertRawProp(context, rawProps, "barCodeScannerEnabled", sourceProps.barCodeScannerEnabled, {false})),
    touchDetectorEnabled(convertRawProp(context, rawProps, "touchDetectorEnabled", sourceProps.touchDetectorEnabled, {false})),
    googleVisionBarcodeDetectorEnabled(convertRawProp(context, rawProps, "googleVisionBarcodeDetectorEnabled", sourceProps.googleVisionBarcodeDetectorEnabled, {false})),
    faceDetectorEnabled(convertRawProp(context, rawProps, "faceDetectorEnabled", sourceProps.faceDetectorEnabled, {false})),
    textRecognizerEnabled(convertRawProp(context, rawProps, "textRecognizerEnabled", sourceProps.textRecognizerEnabled, {false})),
    renderToHardwareTextureAndroid(convertRawProp(context, rawProps, "renderToHardwareTextureAndroid", sourceProps.renderToHardwareTextureAndroid, {false})),
    testID(convertRawProp(context, rawProps, "testID", sourceProps.testID, {false})),
    autoFocus(convertRawProp(context, rawProps, "autoFocus", sourceProps.autoFocus, {AutoFocusMode::ON})),
    autoFocusPointOfInterest(convertRawProp(context, rawProps, "autoFocusPointOfInterest", sourceProps.autoFocusPointOfInterest, {})),
    pictureSize(convertRawProp(context, rawProps, "pictureSize", sourceProps.pictureSize, {""})),
    cameraId(convertRawProp(context, rawProps, "cameraId", sourceProps.cameraId, {""})), // 4.2.1 新增
    type(convertRawProp(context, rawProps, "type", sourceProps.type, {CameraType::BACK})),
    flashMode(convertRawProp(context, rawProps, "flashMode", sourceProps.flashMode, {FlashMode::AUTO})),
    exposure(convertRawProp(context, rawProps, "exposure", sourceProps.exposure, {0.0})),
    captureAudio(convertRawProp(context, rawProps, "captureAudio", sourceProps.captureAudio, {true})),
    useNativeZoom(convertRawProp(context, rawProps, "useNativeZoom", sourceProps.useNativeZoom, {true})),
    zoom(convertRawProp(context, rawProps, "zoom", sourceProps.zoom, {0.0})),
    maxZoom(convertRawProp(context, rawProps, "maxZoom", sourceProps.maxZoom, {0.0})),
    focusDepth(convertRawProp(context, rawProps, "focusDepth", sourceProps.focusDepth, {0.0})),
    detectedImageInEvent(convertRawProp(context, rawProps, "detectedImageInEvent", sourceProps.detectedImageInEvent, {true})),

    googleVisionBarcodeType(convertRawProp(context, rawProps, "googleVisionBarcodeType", sourceProps.googleVisionBarcodeType, {0.0})),
    googleVisionBarcodeMode(convertRawProp(context, rawProps, "googleVisionBarcodeMode", sourceProps.googleVisionBarcodeMode, {0.0})),
    rectOfInterest(convertRawProp(context, rawProps, "rectOfInterest", sourceProps.rectOfInterest, {})),
    faceDetectionMode(convertRawProp(context, rawProps, "faceDetectionMode", sourceProps.faceDetectionMode, {0.0})),
    faceDetectionLandmarks(convertRawProp(context, rawProps, "faceDetectionLandmarks", sourceProps.faceDetectionLandmarks, {0.0})),
    faceDetectionClassifications(convertRawProp(context, rawProps, "faceDetectionClassifications", sourceProps.faceDetectionClassifications, {0.0})),
    trackingEnabled(convertRawProp(context, rawProps, "trackingEnabled", sourceProps.trackingEnabled, {true})),
    ratio(convertRawProp(context, rawProps, "ratio", sourceProps.ratio, {true})),
    playSoundOnCapture(convertRawProp(context, rawProps, "playSoundOnCapture", sourceProps.playSoundOnCapture, {true})),
    playSoundOnRecord(convertRawProp(context, rawProps, "playSoundOnRecord", sourceProps.playSoundOnRecord, {false})), // 4.2.1 新增
    videoStabilizationMode(convertRawProp(context, rawProps, "videoStabilizationMode", sourceProps.videoStabilizationMode, {VideoStabilizationMode::AUTO})),
    defaultVideoQuality(convertRawProp(context, rawProps, "defaultVideoQuality", sourceProps.defaultVideoQuality, {VideoQuality::ONE_ZERO_P})),
    whiteBalance(convertRawProp(context, rawProps, "whiteBalance", sourceProps.whiteBalance, {WhiteBalance::AUTO})),
    keepAudioSession(convertRawProp(context, rawProps, "keepAudioSession", sourceProps.keepAudioSession, {true}))
      {}


} // namespace react
} // namespace facebook
