/**
 * This code was generated by "react-native codegen-lib-harmony"
 */

#include "RNCCameraModule.h"

namespace rnoh {
using namespace facebook;

RNCCameraModule::RNCCameraModule(const ArkTSTurboModule::Context ctx, const std::string name) : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_ASYNC_METHOD_METADATA(getCameraPermission, 0),
        ARK_ASYNC_METHOD_METADATA(getAuidPermission, 0),
        ARK_ASYNC_METHOD_METADATA(getCameraIds, 0),
        ARK_ASYNC_METHOD_METADATA(getAvailablePictureSizes, 0),
    };
}

} // namespace rnoh
